kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    k8s-app: stqbackend
  name: stqbackend
  namespace: default
  annotations:
    secret.reloader.stakater.com/reload: "tradeenv,couchbase,stoqeyenv"
spec:
  replicas: 0
  selector:
    matchLabels:
      k8s-app: stqbackend
  template:
    metadata:
      labels:
        k8s-app: stqbackend    
    spec:
      imagePullSecrets:
        - name: gcr-json-key
      volumes:
        - name: firebase-adminsdk
          secret:
            secretName: bigquery-admin-sa
      containers:
        - name: stqbackend
          image: gcr.io/xxcloud/stqbackend:ffc29b8
          volumeMounts:
            - name: firebase-adminsdk
              mountPath: /build/src/keys
          resources:
            requests:
              cpu: 0.1            
              memory: 312Mi   
            limits:
              cpu: 1            
              memory: 912Mi                               
          env:
            - name: DELAY_SEC
              value: "3"
            - name: DEBUG
              value: "stq*"            
            - name: APP_NAME
              value: "stq"
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3000"
            - name: REDIS_HOST
              value: redis  
            - name: TRADE_ENV
              valueFrom:
                secretKeyRef:
                  name: tradeenv
                  key: TRADE_ENV              
            - name: TZ
              valueFrom:
                secretKeyRef:
                  name: tradeenv
                  key: TZ  
            - name: COUCHBASE_URL
              valueFrom:
                secretKeyRef:
                  name: couchbase
                  key: url      
            - name: COUCHBASE_BUCKET
              valueFrom:
                secretKeyRef:
                  name: couchbase
                  key: bucket
            - name: COUCHBASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: couchbase
                  key: username
            - name: COUCHBASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: couchbase
                  key: password  
            - name: ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: stoqeyenv
                  key: ACCESS_TOKEN_SECRET
            - name: REFRESH_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: stoqeyenv
                  key: REFRESH_TOKEN_SECRET   
            - name: STQNETWORK_WS
              valueFrom:
                secretKeyRef:
                  name: stoqeyenv
                  key: STQNETWORK_WS  
            - name: STQNETWORK
              valueFrom:
                secretKeyRef:
                  name: stoqeyenv
                  key: STQNETWORK   
            - name: PAYPAL_ID
              valueFrom:
                secretKeyRef:
                  name: stoqeyenv
                  key: PAYPAL_ID     
            - name: PAYPAL_SECRET
              valueFrom:
                secretKeyRef:
                  name: stoqeyenv
                  key: PAYPAL_SECRET                                                                                                                                                                                                                                 
                                                                                                                           
          ports:
            - containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /
              port: 3000
            initialDelaySeconds: 30
            timeoutSeconds: 30    
---
# ------------------- Dashboard Service ------------------- #
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: stqbackend
  name: stqbackend
  namespace: default
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    k8s-app: stqbackend
