kind: Deployment
apiVersion: apps/v1
metadata:
  name: dior
  namespace: default
  labels:
    k8s-app: dior
  annotations:
    secret.reloader.stakater.com/reload: 'tradeenv,couchbase,stoqeyenv'
spec:
  replicas: 0
  selector:
    matchLabels:
      k8s-app: dior
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: dior
    spec:
      volumes:
        - name: firebase-adminsdk
          secret:
            secretName: bigquery-admin-sa
            defaultMode: 420
      containers:
        - name: dior
          image: 'gcr.io/xxcloud/dior-dev:eeb052a'
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: DEBUG
              value: dior*
            - name: APP_NAME
              value: dior
            - name: NODE_ENV
              value: production
            - name: PORT
              value: '3000'
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: sentry
                  key: dior
            - name: TZ
              valueFrom:
                secretKeyRef:
                  name: tradeenv
                  key: TZ
            - name: COUCHBASE_URL
              valueFrom:
                secretKeyRef:
                  name: couchbase
                  key: url
            - name: COUCHBASE_BUCKET
              valueFrom:
                secretKeyRef:
                  name: couchbase
                  key: bucket
            - name: COUCHBASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: couchbase
                  key: username
            - name: COUCHBASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: couchbase
                  key: password
            - name: ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: stoqeyenv
                  key: ACCESS_TOKEN_SECRET
            - name: REFRESH_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: stoqeyenv
                  key: REFRESH_TOKEN_SECRET
          resources:
            limits:
              cpu: '1'
              memory: 912Mi
            requests:
              cpu: 100m
              memory: 312Mi
          volumeMounts:
            - name: firebase-adminsdk
              mountPath: backend/build/keys
          livenessProbe:
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
        - name: gcr-json-key
      schedulerName: default-scheduler
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
# ------------------- Dashboard Service ------------------- #
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: dior
  name: dior
  namespace: default
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    k8s-app: dior
